# _config.yml
title: "Matthew Santos"
description: "The personal portfolio of Matthew Santos, an electrical engineer specializing in sensor systems. View engineering projects, technical expertise, and career acomplishments."
repository: "Matt-Santos/matt-santos.github.io"

# Jekyll Build settings
timezone: America/Toronto
theme: null #jekyll-theme-minimal
markdown: GFM

# Varriables
author:
 name: "Matthew Santos"
 location: "Milton, Ontario"
 email: "mailto:contact@msantos.ca"
 location: "Toronto, Ontario"
 github: "https://github.com/matt-santos"
 linkedin: "https://linkedin.com/in/matthewjsantos"
 orcid: "https://orcid.org/0009-0006-1653-3882"